version: '3'

services:
  ideas-api:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8080:8080'
      working_dir: /ideas-api
      volumes:
        - ./ideas-api:/ideas-api
      depends_on:
        - postgresdev
      command: './gradlew bootRun'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=pgdev



  dogs-ui:
    build: ./dogs-ui
    ports:
      - 3000:3000
    volumes:
      - ./dogs-ui/src:/usr/src/app/src
      - ./dogs-ui/public:/usr/src/app/public
    links:
        - dogs
  cats-ui:
    build: ./cats-ui
    expose:
      - 6000
    ports:
      - 6000:5500
    volumes:
      - ./cats-ui/src:/usr/src/app/src
      - ./cats-ui/public:/usr/src/app/public
    links:
        - cats